#!/bin/bash

opkg update
clear

wget -O config.ipk https://github.com/chalyyzhu/argon_theme/raw/main/luci-app-argon-config_0.8-beta_all.ipk
echo "[+] install argon config.."
opkg install config.ipk

wget -O argon.ipk https://github.com/chalyyzhu/argon_theme/raw/main/luci-theme-argon-master_2.2.9.4_all.ipk
echo "[+] install argon theme.."
opkg install argon.ipk

wget -O /usr/lib/lua/luci/view/themes/argon/footer.htm https://raw.githubusercontent.com/chalyyzhu/argon_theme/main/footer.htm

echo "[+] INSTALLATION ARGON THEME SUCESS.."
